	IMPORT mapper0init
	IMPORT mapper1init
	IMPORT mapper2init
	IMPORT mapper3init
	IMPORT mapper4init
	IMPORT mapper5init
	IMPORT mapper7init
	IMPORT mapper9init
	IMPORT mapper10init
	IMPORT mapper11init
	IMPORT mapper15init
	IMPORT mapper16init
	IMPORT mapper17init
	IMPORT mapper18init
	IMPORT mapper19init
	IMPORT mapper21init
	IMPORT mapper22init
	IMPORT mapper23init
	IMPORT mapper24init
	IMPORT mapper25init
	IMPORT mapper26init
	IMPORT mapper32init
	IMPORT mapper33init
	IMPORT mapper34init
	IMPORT mapper40init
	IMPORT mapper64init
	IMPORT mapper65init
	IMPORT mapper66init
	IMPORT mapper67init
	IMPORT mapper68init
	IMPORT mapper69init
	IMPORT mapper70init
	IMPORT mapper71init
	IMPORT mapper72init
	IMPORT mapper73init
	IMPORT mapper75init
	IMPORT mapper76init
	IMPORT mapper77init
	IMPORT mapper78init
	IMPORT mapper79init
	IMPORT mapper80init
	IMPORT mapper85init
	IMPORT mapper86init
	IMPORT mapper87init
	IMPORT mapper92init
	IMPORT mapper93init
	IMPORT mapper94init
	IMPORT mapper97init
	IMPORT mapper99init
	IMPORT mapper105init
	IMPORT mapper151init
	IMPORT mapper152init
	IMPORT mapper180init
	IMPORT mapper184init
	IMPORT mapper228init
	IMPORT mapper232init

	IMPORT mapper9BGcheck
	END
